# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
        ROLE_ADMIN: [ROLE_MOD]
        ROLE_MOD: [ROLE_USER]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        users:
            entity: { class: AppBundle\Entity\User, property: username }

        twitch_users:
            id: AppBundle\Security\TwitchUserProvider



    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - AppBundle\Security\LoginFormAuthenticator
            simple_preauth:
                authenticator: AppBundle\Security\TwitchAuthenticator
            provider: twitch_users

            logout:
                path: /logout

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }