<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Profile extends \AppBundle\Entity\Profile implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_id', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_avatar', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_bio', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_issub', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_subplan', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_subsince'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_id', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_avatar', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_bio', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_issub', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_subplan', '' . "\0" . 'AppBundle\\Entity\\Profile' . "\0" . 'profile_subsince'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Profile $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getProfileId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileId', []);

        return parent::getProfileId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileId($profile_id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileId', [$profile_id]);

        return parent::setProfileId($profile_id);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileAvatar', []);

        return parent::getProfileAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileAvatar($profile_avatar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileAvatar', [$profile_avatar]);

        return parent::setProfileAvatar($profile_avatar);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileBio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileBio', []);

        return parent::getProfileBio();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileBio($profile_bio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileBio', [$profile_bio]);

        return parent::setProfileBio($profile_bio);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileIssub()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileIssub', []);

        return parent::getProfileIssub();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileIssub($profile_issub = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileIssub', [$profile_issub]);

        return parent::setProfileIssub($profile_issub);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileSubplan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileSubplan', []);

        return parent::getProfileSubplan();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileSubplan($profile_subplan = 0)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileSubplan', [$profile_subplan]);

        return parent::setProfileSubplan($profile_subplan);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfileSubsince()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfileSubsince', []);

        return parent::getProfileSubsince();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfileSubsince($profile_subsince)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfileSubsince', [$profile_subsince]);

        return parent::setProfileSubsince($profile_subsince);
    }

}
